name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Install dependencies
        run: go mod tidy

      - name: Build Linux AMD64 binary
        run: |
          mkdir -p build
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/fsa main.go

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fsa-binary
          path: build/fsa

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fsa-binary
          path: .

      - name: Deploy to Oracle VPS
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@137.131.221.149 "sudo service fsa stop"
          scp -o StrictHostKeyChecking=no -i private_key.pem ./fsa ubuntu@137.131.221.149:~/fsa/fsa
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@137.131.221.149 "sudo service fsa start"
          rm -f private_key.pem

    permissions:
      contents: read
